repos:
-   repo: https://github.com/ambv/black
    rev: 25.9.0
    hooks:
    - id: black
      language_version: python3
-   repo: https://github.com/PyCQA/flake8
    rev: 7.3.0
    hooks:
    - id: flake8
